### ISSUE TITLE
Tier 3 error  - Calculating EucDistance GUT

### ISSUE THREAD

**Issue by EllieCrabbe** [Riverscapes/pyGUT#2]
Hello, 

I have successfully run Tier 2 and 3 of GUT however PyGUT is unable to complete Tier 3. My projection is British National Grid and DEM 0.25 resolution of  I have attempted to run only tier 3, reduce the resolution of my DEM but Arc error 99999 still pops up. 

Any ideas why Tier 3 won't run, more specifically EucDistance ?
 
Many thanks

**Comment by joewheaton** [comment]
@EllieCrabbe that is a tough one.  We know the current version of GUT has memory issues. We've broken bigger projects into smaller segments to get it to run previously. It is surprising to me it is crashing there. @bangen may have some ideas, but she's no longer working for us so not sure if she'll be able to respond. If you want to record a video and post a youTube link to what you're experiencing we might see something. Unfortunately, as powerful conceptually as GUT is, and as well as it can work, it is not actively under development.  Hopefully we'll secure some funding to move it from a fragile research-grade tool (works well with really clean consistent data), into a production grade tool. However,  I suspect that will not help you in the short term. Sorry not to have better news....

**Comment by EllieCrabbe** [comment]
Hi all, thanks so much for getting back to me. @bangen has been really helpful and told me those aforementioned suggestions but i didn't have any luck with them. I'll see if I can post a video to try and describe the issue a little better. I really appreciate the response and will have play around with my data to see if I can get it through tier 3. Will let you know if I get anywhere. I look forward to seeing how GUT develops, as and when you secure your funding. Good luck!

**Comment by joewheaton** [comment]
This has quieted down. Closing. Feel free to re-open @EllieCrabbe if still stuff to resolve.
